In [10]:
import numpy as np

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('size of an array:',a.size)
print("Type of a:",type(a))
print("Dimensions of an array:",a.ndim)

[[1 2 3]
 [4 5 6]]
size of an array: 6
Type of a: <class 'numpy.ndarray'>
Dimensions of an array: 2


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,20,30]])
print(a)
print('size of an array:',a.size)
print("Type of a:",type(a))
print("Dimensions of an array:",a.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
size of an array: 12
Type of a: <class 'numpy.ndarray'>
Dimensions of an array: 2


In [13]:
import numpy as np
import pandas as pd
pd.__version__

'1.2.4'

In [14]:
# list
l=[10,20,30,40]
s=pd.Series(l)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [15]:
a=np.array([1,2,3,4,5,8,])
s=pd.Series(a)
s

0    1
1    2
2    3
3    4
4    5
5    8
dtype: int32

In [16]:
a=np.array([1,2,3,4,5,8,"ashu"])
s=pd.Series(a)
s

0       1
1       2
2       3
3       4
4       5
5       8
6    ashu
dtype: object

In [17]:
a=np.array([1,2,3,4,5,8,10.5])
s=pd.Series(a)
s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     8.0
6    10.5
dtype: float64

In [18]:
a=np.array([10.5,20.5,30.5,40.5,9])
s=pd.Series(a)
s

0    10.5
1    20.5
2    30.5
3    40.5
4     9.0
dtype: float64

In [19]:
a=np.array([1,"ashu",20.5,True])
s=pd.Series(a)
s

0       1
1    ashu
2    20.5
3    True
dtype: object

In [20]:
type(s)

pandas.core.series.Series

In [21]:
s.dtype

dtype('O')

In [22]:
a=b"Welcome to Numpy"
a


b'Welcome to Numpy'

In [23]:
import numpy as np
a=b"Welcome to Numpy"
a

np.frombuffer(a,dtype="S1",count=2,offset=9)

array([b'o', b' '], dtype='|S1')

In [24]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [25]:
a=np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
np.zeros([2,3,4])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.full([2,3],[9])

array([[9, 9, 9],
       [9, 9, 9]])

In [28]:
np.full([2,3,4],[10])

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [29]:
np.random.rand(2,3)

array([[0.12427566, 0.94485814, 0.90450611],
       [0.06437384, 0.52758967, 0.75689938]])

In [30]:
np.ones([2,5,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# list to DataFrame
l=[10,20,30,40,50,60]
df=pd.DataFrame(l)
df

0
0  10
1  20
2  30
3  40
4  50
5  60

In [33]:
a=[[10,20,30,],[40,50,60],[70,80,90],[100,110,120]]
df=pd.DataFrame(l)
df

0
0  10
1  20
2  30
3  40
4  50
5  60

In [34]:
l=[['sai',30],['rahul',25]]
df=pd.DataFrame(l,columns=['name','age'])
df

name  age
0    sai   30
1  rahul   25

In [35]:
import numpy as np
import pandas as pd


In [36]:
# list of tuples into dataframe

l=[('a',23),('b',34),('c',23),('d',67)]
df=pd.DataFrame(l,columns=['name','age'])
df

name  age
0    a   23
1    b   34
2    c   23
3    d   67

In [37]:
# numpy array to dataframe

l=np.array([['a',23],['b',34],['c',45]])
df=pd.DataFrame(l,columns=['name','age'])
df

name age
0    a  23
1    b  34
2    c  45

In [38]:
# dictionary to dataframe

d={'name':['a','b','c','d','e'],'age':[10,20,30,40,50]}
df=pd.DataFrame(d)
df

name  age
0    a   10
1    b   20
2    c   30
3    d   40
4    e   50

In [39]:
d["name"]

['a', 'b', 'c', 'd', 'e']

In [40]:
d={'name':['a','b','c','d','e','f','g','h'],
  'age':[23,24,25,26,27,28,29,30],
  'marks':[80,83,94,54,85,54,62,25]}
df=pd.DataFrame(d)
df

name  age  marks
0    a   23     80
1    b   24     83
2    c   25     94
3    d   26     54
4    e   27     85
5    f   28     54
6    g   29     62
7    h   30     25

In [41]:
d={'num':[101,102,103],'name':['a','b','c']}
df=pd.DataFrame(d,index=['i','ii','iii'])
df

num name
i    101    a
ii   102    b
iii  103    c

In [42]:
d={'name':['a','b','c','d','e','f','g','h'],
  'age':[23,24,25,26,27,28,29,30],
  'marks':[80,83,94,54,85,54,62,25]}
df=pd.DataFrame(d)
df['sadd']=['hyd','kok','ben','vizag','gun','prak','chi','kar']
df['father name']=['chi','anj','sri','kir','ram','jav','rav','valli']
df

name  age  marks   sadd father name
0    a   23     80    hyd         chi
1    b   24     83    kok         anj
2    c   25     94    ben         sri
3    d   26     54  vizag         kir
4    e   27     85    gun         ram
5    f   28     54   prak         jav
6    g   29     62    chi         rav
7    h   30     25    kar       valli

In [43]:
a=df[['name','sadd']]
a

name   sadd
0    a    hyd
1    b    kok
2    c    ben
3    d  vizag
4    e    gun
5    f   prak
6    g    chi
7    h    kar

In [44]:


a=df[3:]
a


a=df[1:4]
a


name  age  marks   sadd father name
1    b   24     83    kok         anj
2    c   25     94    ben         sri
3    d   26     54  vizag         kir

In [45]:
# access the data using loc and iloc

* loc -> location
* iloc -> INDEX LOCATION

SyntaxError: invalid syntax (<ipython-input-45-a74283a6c1b8>, line 3)

In [65]:
a=df.loc[3]
print(a)


a=df.iloc[3]
a

name             d
age             26
marks           54
father name    kir
Name: 3, dtype: object


name             d
age             26
marks           54
father name    kir
Name: 3, dtype: object

In [2]:
import numpy as np
import pandas as pd

d={'name':['a','b','c','d','e','f','g','h'],
  'age':[23,24,25,26,27,28,29,30],
  'marks':[80,83,94,54,85,54,62,25]}
df=pd.DataFrame(d)
df['father name']=['chi','anj','sri','kir','ram','jav','rav','valli']
df

name  age  marks father name
0    a   23     80         chi
1    b   24     83         anj
2    c   25     94         sri
3    d   26     54         kir
4    e   27     85         ram
5    f   28     54         jav
6    g   29     62         rav
7    h   30     25       valli

In [3]:
df['father name']=['chi','anj','sri','kir','ram','jav','rav','valli']
df

name  age  marks father name
0    a   23     80         chi
1    b   24     83         anj
2    c   25     94         sri
3    d   26     54         kir
4    e   27     85         ram
5    f   28     54         jav
6    g   29     62         rav
7    h   30     25       valli

In [51]:
df=pd.DataFrame(d,columns=['name','father name'])
df

name father name
0    a         NaN
1    b         NaN
2    c         NaN
3    d         NaN
4    e         NaN
5    f         NaN
6    g         NaN
7    h         NaN

# * DATE 09-07-2021

# # TODAY OBJECT
* HOW TO ACCESS THE DATA USING CONDATION
* HOW TO CREATE DATA FRAME USINF FILES
   * CSV
   * EXCEL
   * JSON
   * HTML 

In [9]:
import numpy as np
import pandas as pd

d={'sno':[101,102,103,104,105,106,107,108,109,110],
  'sname:'['a','b','c','d','e','f','g','h','i','j'],
  'sage:'[10,20,30,40,50,60,70,80,90,100]}
df=pd.DataFrame(d)
df


SyntaxError: invalid syntax (<ipython-input-9-349d87bde82a>, line 5)

In [11]:
d={'name':['a','b','c','d','e','f','g','h'],
  'age':[23,24,25,26,27,28,29,30],
  'marks':[80,83,94,54,85,54,62,25]}
df=pd.DataFrame(d)
df

name  age  marks
0    a   23     80
1    b   24     83
2    c   25     94
3    d   26     54
4    e   27     85
5    f   28     54
6    g   29     62
7    h   30     25

In [ ]:
df[df['sno']== ]

In [ ]:
##  TASK

* 

### How to access the